const configurationActions = {
  CONFIGURATION_LIST_REQUEST: 'CONFIGURATION_LIST_REQUEST',
  CONFIGURATION_LIST_SUCCESS: 'CONFIGURATION_LIST_SUCCESS',
  CONFIGURATION_LIST_ERROR: 'CONFIGURATION_LIST_ERROR',
  getList: () => ({
    type: configurationActions.CONFIGURATION_LIST_REQUEST,
  }),
  CONFIGURATION_DETAILS_REQUEST: 'CONFIGURATION_DETAILS_REQUEST',
  CONFIGURATION_DETAILS_SUCCESS: 'CONFIGURATION_DETAILS_SUCCESS',
  CONFIGURATION_DETAILS_ERROR: 'CONFIGURATION_DETAILS_ERROR',
  getDetails: payload => ({
    type: configurationActions.CONFIGURATION_DETAILS_REQUEST,
    payload
  })
};

export default configurationActions;